CREATE TABLE EMPLEADOS (
    ID_RUT INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    FECHA_NAC DATE,
    FECHA_CONTRATO DATE,
    SALARIO INT,
    CORREO VARCHAR(50),
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(100),
    ID_ROL INT,
    ID_TIPO INT,
    NOM_USUARIO VARCHAR(50),
    PASSWORD VARCHAR(255),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_EMPLEADO(ID_TIPO)
);

